language:
- python
python:
- '3.4.3'
install:
- pip install -e .
- pip install coveralls
before_script:
- psql -c "CREATE DATABASE loadstone;" -U postgres
script:
- coverage run -m py.test
after_success:
- coveralls
cache:
  directories:
  - $HOME/.cache/pip
notifications:
  email:
    recipients:
    - s.elahmadie@gmail.com
    on_success: change
    on_failure: always